name: Scheduled Ping to Keep Apps Awake
on:
  schedule:
    - cron: '0 */10 * * *'
  workflow_dispatch: 

jobs:
  ping_job:
    runs-on: ubuntu-latest
    steps:
      - name: Ping App 1: fzwigepq746bvjjgpjntu7
        uses: soul-wish/ping-url-javascript-action@v1.5 
        with:
          url: 'https://ps-gen-app-fzwigepq746bvjjgpjntu7.streamlit.app/'

      - name: Ping App 2: lgn5tcwnjfuu4hankxgjwc
        uses: soul-wish/ping-url-javascript-action@v1.5 
        with:
          url: 'https://ps-gen-app-lgn5tcwnjfuu4hankxgjwc.streamlit.app/'
